name: firebase deploy

on:
  push:
    paths:
      - ".env*"
      - ".firebaserc"
      - ".github/workflows/nodejs.yml"
      - "firebase.json"
      - "package-lock.json"
      - "public/**"
      - "src/**"

permissions:
  contents: read
  id-token: write
  deployments: write

concurrency:
  group: '${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v3

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm

      - name: 📥 Download dependencies
        run: npm ci

      - name: 🧪 Run tests
        run: npm test

      - name: 🧹 Lint
        run: npm run lint

  deploy-dev:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: dev
      url: https://vista-map.dev.utah.gov
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v3

      - id: auth
        name: 🗝️ Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.7.0
        with:
          access_token_scopes: 'email, openid, https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase'
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          create_credentials_file: true

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: .node-version
          cache: npm

      - name: 📥 Download dependencies
        run: npm ci

      - name: 🏗 Run build script
        run: npm run build:stage

      - name: 🪣 Cache firebase
        uses: actions/cache@v3
        with:
          path: ./.firebase
          key: ${{ runner.OS }}-firebase-${{ hashFiles('**/*.cache') }}
          restore-keys: |
            ${{ runner.OS }}-firebase-
            ${{ runner.OS }}-

      - name: 🚀 Firebase deploy
        run: >
          npx firebase-tools deploy
          --only hosting
          --project ${{ secrets.PROJECT_ID }}
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

  deploy-prod:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: prod
      url: https://vista-map.ugrc.utah.gov
    if: github.ref == 'refs/heads/main'

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v3

      - id: auth
        name: 🗝️ Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.7.0
        with:
          access_token_scopes: 'email, openid, https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase'
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          create_credentials_file: true

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: .node-version
          cache: npm

      - name: 📥 Download dependencies
        run: npm ci

      - name: 🏗 Run build script
        run: npm run build:prod

      - name: 🪣 Cache firebase
        uses: actions/cache@v3
        with:
          path: ./.firebase
          key: ${{ runner.OS }}-firebase-${{ hashFiles('**/*.cache') }}
          restore-keys: |
            ${{ runner.OS }}-firebase-
            ${{ runner.OS }}-

      - name: 🚀 Firebase deploy
        run: >
          npx firebase-tools deploy
          --only hosting
          --project ${{ secrets.PROJECT_ID }}
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
